import { defineConfig } from 'tsup';

export default defineConfig({
    entry: ['src/index.ts'],
    format: ['esm'],
    target: 'node22',
    outDir: 'dist',
    clean: true,
    splitting: false,
    dts: false,
    sourcemap: true,
    banner: { js: '#!/usr/bin/env node\nimport{createRequire}from"module";const require=createRequire(import.meta.url);' },
    external: [
        'better-sqlite3',
        'node-llama-cpp',
        'yoga-wasm-web',
        'yoga-layout',
        'ink',
        'ink-text-input',
        'ink-spinner',
        'react',
        'react/jsx-runtime',
        'react/jsx-dev-runtime',
        'react-devtools-core',
        'react-reconciler',
    ],
    noExternal: [
        'chalk',
        'commander',
        'chrono-node',
        'cli-table3',
        'date-fns',
        'figures',
        'fuse.js',
        'marked',
        'marked-terminal',
        'ora',
        'conf',
        'terminal-link',
    ],
});
